### ISSUE TITLE
Overcoming 'cssta' limitations

### ISSUE THREAD

**Issue by Dattaya** [jacobp100/cssta#1]
I'm not familiar with `styled-componenst` and `cssta` internals, so forgive me if I'm starting a useless discussion.

> interpolation (${value}) is not supported on web, but is supported for React Native

What about using Apollo's (Graphql) approach: a query could be written completely in js or as a string:
```graphql
const query = gql`
  query Repos($login: String) {
    repos(login: $login) {
      name
    }
}`;
```
and here, instead of putting variables/functions/... directly into the template literal, you would do that in a decorator:
```js
const HomePageWithData = graphql(query, {
  options: ({ login }) => ({ variables: { login }, noFetch: !login }),
}
)(HomePage);
``` 

I'm wondering, does it make any sense to do the same with css?

```js
const style = cssta.button`
  color: var(--primaryColor, darkcyan);
  padding: 0.5rem 1rem;
  border: 2px solid currentColor;
  border-radius: 1000px;
`;

const HomePageStyled = cssta(style, (props, theme) =>
  ({ primaryColor : props.loading ? theme.orange : theme.green })
)(HomePage);
```

Are there advantages to this approach compared to `styled-components`'s? Is it possible to still compile everything on the server with postcss to js instead of polluting front end with all those libraries.

**Comment by jacobp100** [comment]
I think I understood your question: you wanted to know if variables could be supported like in CSS, but with the variables defined in JS.

Currently, we don’t allow interpolation on the web, because we generate a real static CSS file, which cannot be changed at a later point via JS. But it is a real CSS file, so you can use CSS variables in browsers that support them (all major ones but Edge).

But this is also actually something I am actively considering—especially for Native where you cannot use variables to theme. There is also no reason why we can’t generate real CSS files for the styles that don’t depend on variables, and dynamically inject styles for the ones that do (as styled-components currently does).

I do want to enable more dynamism in the project, but I want to be careful in what I enable. I want there to be one obvious way to do something.

My current line of thought is pretty much what you posted: CSS variables, and enabling a JS fallback for both React Native (always required), and for web if you want full theming support browsers that do not support native variables. But nothing yet is fleshed out enough for me to actually implement anything.

**Comment by Dattaya** [comment]
With regard to modern browsers it's almost ready, this is what I have in mind after what you've written:
 - give unique names to variables to avoid collision with other components.
 - provide a function that will inject new variable values dynamically into `CSSStyleSheet` in `<head>` based on `props` and `theme` objects, so this code:
```js
const Button = cssta(style, (props, theme) =>
  ({ primaryColor : props.loading ? theme.orange : theme.green })
)(HomePage);
```
would result to this in production (provided `props.loading` is `true` and `theme.orange` is `orange`):
```
:root {
  --uniqueHashedVariableName: orange;  
}
```

For IE even this simple function: https://github.com/polyfills/variables/blob/master/index.js will do the job, it's going to be a bit slow during initial load I guess, but IE is dying anyway ([Edge will support CSS Variables soon.](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6261292-css-variables)) However being slow is not acceptable for React Native.

**Comment by jacobp100** [comment]
I think it would be slightly different. The variables would be the theme variables. Maybe the example would look more like this,

```js
const Button = cssta.button`
  color: var(--green);

  [loading] {
    color: var(--orange);
  }
`;
```

And you can already get quite far with this via,

```js
cssta.injectGlobal`
  --orange: #f80;
  --green: #0f0;
`;

// or

const ThemeProvider = ({ children }) => <div style="--orange: blue;">{children}</div>;
```

**Comment by Dattaya** [comment]
That looks better and probably easier to implement. I thought that someone might want a private, not globally exposed variable, to compute it, say, only from `props`, not touching theme, maybe that's not a real  life case.

**Comment by jacobp100** [comment]
I think it is a real use case, but it’s limited enough that you can probably just manually set the `style` property. This still works:

```js
const Button = cssta.button`…`;
<Button style={{ backgroundColor: ‘blue’ }} />
```

**Comment by jacobp100** [comment]
Just an update on this, I’ve added CSS custom properties to the React Native version: [see this example](https://github.com/jacobp100/cssta/blob/master/CsstaNativeDemo/App.js)

You can read a bit more about theming in [the docs](https://jacobp100.gitbooks.io/cssta/content/theming.html).

I’ll publish the changes to enable custom properties for React Native in the next few days.

**Comment by Dattaya** [comment]
That's awesome, thanks for the update and the links. I thinks I can close this issue now.
